name: Lint Markdown Files

on:
  push:
    paths:
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install -g proselint write-good

      - name: Lint Markdown Files
        run: |
          for file in $(find . -name "*.md"); do
            proselint "$file" || exit 1
            write-good "$file" || exit 1
          done
